name: Model Training Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: 
  contents: write  # Required for artifact deletion

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Clean previous artifacts
      run: |
        rm -rf models/*
        rm -rf artifacts/*

    - name: Delete existing GitHub artifact
      run: |
        ARTIFACT_ID=$(gh api repos/${{ github.repository }}/actions/artifacts --jq '.artifacts[] | select(.name=="training-results") | .id')
        if [ -n "$ARTIFACT_ID" ]; then
          gh api -X DELETE repos/${{ github.repository }}/actions/artifacts/$ARTIFACT_ID
          echo "Deleted old artifact ID: $ARTIFACT_ID"
        else
          echo "No existing artifact found."
        fi
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
        echo "VIRTUAL_ENV=venv" >> $GITHUB_ENV
        echo "source venv/bin/activate" >> ~/.bashrc

    - name: Install dependencies
      run: |
        source venv/bin/activate
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Run model training
      run: |
        source venv/bin/activate
        python src/model.py

    - name: Debug - Check Generated Files
      run: ls -R models artifacts || echo "No files found!"

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: training-results
        path: |
          models/logistic_regression_model.pkl
          artifacts/classification_report.jpeg
          artifacts/heatmap.jpeg
        if-no-files-found: ignore
