name: Model Training Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: 
  contents: write

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Install dependencies
      run: |
        source venv/bin/activate
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Run model training
      run: |
        source venv/bin/activate
        python src/model.py

    - name: Commit and push updated model
      env:
        GIT_COMMITTER_NAME: codehax41
        GIT_COMMITTER_EMAIL: ramsundar.1238@gmail.com
      run: |
        git config --global user.name "codehax41"
        git config --global user.email "ramsundar.1238@gmail.com"
  
        git add -A
        git commit -m "commit message"
        git push

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: training-results
        path: |
          models/logistic_regression_model.pkl
          artifacts/classification_report.jpeg
          artifacts/heatmap.jpeg
        overwrite: true
