name: Model Training Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: 
  contents: write  # 🔥 Grants write access to upload artifacts

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
        echo "VIRTUAL_ENV=venv" >> $GITHUB_ENV
        echo "source venv/bin/activate" >> ~/.bashrc

    - name: Install dependencies
      run: |
        source venv/bin/activate
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Ensure directories exist
      run: |
        mkdir -p models1 artifacts1

    - name: Run model training
      run: |
        source venv/bin/activate
        python src/model.py

    - name: Debug - Check Generated Files
      run: ls -R models1 artifacts1 || echo "No files found!"

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: training-results
        path: |
          models1/logistic_regression_model.pkl
          artifacts1/classification_report.jpeg
          artifacts1/heatmap.jpeg
